# app.yaml
runtime: nodejs20 
env: standard    
service: default 

# আপনার অ্যাপ্লিকেশন চালু করার কমান্ড
entrypoint: npm start

# পরিবেশ চলক (Environment Variables) - এটি যোগ করা অত্যন্ত জরুরি
env_variables:
  SUPABASE_URL: "https://edboiyrmhpbihsuwccxk.supabase.co"
  SUPABASE_KEY: "sb_publishable_EpE2CALYA4av_iugcbElnA_KIvEP2V-"
  EMAILJS_PUBLIC_KEY: "Fak1n43FGudoNISD3"
  EMAILJS_SERVICE_ID: "service_pqj8mqx"
  EMAILJS_TEMPLATE_ID: "template_f9xekrr"
  WELCOME_TEMPLATE_ID: "template_h9cfxf9"
  GOOGLE_MAPS_API_KEY: "AIzaSyAn1NUDgVU3HjgEUvVR5CDHhnUrPfhUQ9A"
  GEMINI_API_KEY: "AIzaSyBOUijFeHdFdH--NhAkkjHCmvKXKSi_Sq8"
  PORT: "8080"

# মেমরি এবং সিপিইউ কনফিগারেশন
instance_class: F1

# হ্যান্ডলার (URL Routing)
handlers:
- url: /.*
  script: auto
